[project]
name = 'Cosmic-Evolutionary-Guidance-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.civilizational-development]
path = 'contracts/civilizational-development.clar'
clarity_version = 2
epoch = 2.5

[contracts.galactic-seed-placement]
path = 'contracts/galactic-seed-placement.clar'
clarity_version = 2
epoch = 2.5

[contracts.interspecies-collaboration]
path = 'contracts/interspecies-collaboration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
